mod_pot_bhc Module Reference
mod_pot_bhc Module Reference
This module performs BH + COULOMBIC potential calculations.
Data Types
type bhc_atom
type bhc_dimer
type bhc_molecule
Functions/Subroutines
subroutine read_bhc_params (this, bhc_filename, numat)
This routine reads all necessary parameters from files.
subroutine check_bhc_params (this, mol, numat, bhc_filename)
This routine checks for inconsistent entries on parameter files.
subroutine calc_bhc_cross (this)
This routine calculates crossing values for BH + coulomb potential before the loops.
subroutine calc_bhc_energy (this, g, r, t)
This routine performs energy calculations and returns VTOT(p,r,t).
Variables
type(bhc_molecule) mol1_bhc
type(bhc_molecule) mol2_bhc
type(bhc_dimer) bhc_dimers
Detailed Description
This module performs BH + COULOMBIC potential calculations.
Author
Felippe M. Colombari
Laboratório de Química Teórica, LQT – UFSCar
Date
- Oct, 2017
module created
Note
Buckingham potential used is the one by MATSUI (1991)
added error_handling
Date
- Nov 2019
Function/Subroutine Documentation
calc_bhc_cross()
subroutine mod_pot_bhc::calc_bhc_cross (class(bhc_dimer), intent(inout) this)
This routine calculates crossing values for BH + coulomb potential before the loops.
Author
Felippe M. Colombari
Definition at line 170 of file mod_pot_bhc.f90.
References mod_constants::ccon, mod_read_molecules::mol1, mol1_bhc, mod_read_molecules::mol2, and mol2_bhc.
calc_bhc_energy()
subroutine mod_pot_bhc::calc_bhc_energy (class(bhc_dimer), intent(inout) this, integer, intent(in) g, integer, intent(in) r, integer, intent(in) t)
This routine performs energy calculations and returns VTOT(p,r,t).
Author
Felippe M. Colombari
Laboratório de Química Teórica, LQT – UFSCar
Date
- Jun, 2017
first version
- Oct, 2017
modular subroutine created
Definition at line 224 of file mod_pot_bhc.f90.
References mod_input_read::atom_overlap, mod_input_read::inter_energy, mod_read_molecules::mol1, mod_read_molecules::mol2, mod_input_read::rcut_sqr, and mod_input_read::scale_factor.
check_bhc_params()
subroutine mod_pot_bhc::check_bhc_params (class(bhc_molecule), intent(inout) this, integer, intent(in) mol, integer, intent(in) numat, character(len = *), intent(in) bhc_filename)
This routine checks for inconsistent entries on parameter files.
Author
Felippe M. Colombari
Definition at line 116 of file mod_pot_bhc.f90.
References mod_constants::dashline.
read_bhc_params()
subroutine mod_pot_bhc::read_bhc_params (class(bhc_molecule), intent(inout) this, character(len = *), intent(in) bhc_filename, integer, intent(in) numat)
This routine reads all necessary parameters from files.
Author
Felippe M. Colombari
Laboratório de Química Teórica, LQT – UFSCar
Date
- Jun, 2017
subroutine created
Note
Files read are:
parameters1: contains atomic charges, A, B and C values for molecule 1
parameters2: contains atomic charges, A, B and C values for molecule 2
Definition at line 59 of file mod_pot_bhc.f90.
References mod_constants::dashline, and mod_inquire::inquire_file().
Variable Documentation
bhc_dimers
type(bhc_dimer) mod_pot_bhc::bhc_dimers
Definition at line 43 of file mod_pot_bhc.f90.
mol1_bhc
type(bhc_molecule) mod_pot_bhc::mol1_bhc
Definition at line 33 of file mod_pot_bhc.f90.
Referenced by mod_loops::calc(), calc_bhc_cross(), and mod_deallocate_all::deallocate_arrays().
mol2_bhc
type(bhc_molecule) mod_pot_bhc::mol2_bhc
Definition at line 33 of file mod_pot_bhc.f90.
Referenced by mod_loops::calc(), calc_bhc_cross(), and mod_deallocate_all::deallocate_arrays().