mod_pot_ljc_pair Module Reference
mod_pot_ljc_pair Module Reference
This module performs LJ + coulombic potential calculations.
Data Types
type ljc_pair_dimer
Functions/Subroutines
subroutine read_ljc_pair_params (this, ljc_pair_filename)
This routine reads atom names, charges, sigma and epsilon values from parameter files.
subroutine calc_ljc_pair_cross (this)
This routine calculates crossing values for LJ + coulomb potential before the loops.
subroutine calc_ljc_pair_energy (this, g, r, t)
This routine calculates LJ + coulomb energy for each valid configuration.
Variables
type(ljc_pair_molecule) mol2_ljc_pair
type(ljc_pair_dimer) ljc_pair_dimers
Detailed Description
This module performs LJ + coulombic potential calculations.
Author
Felippe M. Colombari
Laboratório de Química Teórica, LQT – UFSCar
Date
- Oct, 2017
module created
Note
added error_handling
Date
- Nov 2019
Function/Subroutine Documentation
calc_ljc_pair_cross()
subroutine mod_pot_ljc_pair::calc_ljc_pair_cross (class(ljc_pair_dimer), intent(inout) this)
This routine calculates crossing values for LJ + coulomb potential before the loops.
Author
Felippe M. Colombari
Definition at line 115 of file mod_pot_ljc_pair.f90.
References mod_constants::ccon, ljc_pair_dimers, mod_read_molecules::mol1, and mod_read_molecules::mol2.
calc_ljc_pair_energy()
subroutine mod_pot_ljc_pair::calc_ljc_pair_energy (class(ljc_pair_dimer), intent(inout) this, integer, intent(in) g, integer, intent(in) r, integer, intent(in) t)
This routine calculates LJ + coulomb energy for each valid configuration.
Author
Felippe M. Colombari
Definition at line 162 of file mod_pot_ljc_pair.f90.
References mod_input_read::atom_overlap, mod_input_read::cutoff_sqr, mod_input_read::inter_energy, mod_read_molecules::mol1, mod_read_molecules::mol2, mod_input_read::rcut_sqr, and mod_input_read::scale_factor.
read_ljc_pair_params()
subroutine mod_pot_ljc_pair::read_ljc_pair_params (class(ljc_pair_dimer), intent(inout) this, character(len = *), intent(in) ljc_pair_filename)
This routine reads atom names, charges, sigma and epsilon values from parameter files.
Author
Felippe M. Colombari
Definition at line 54 of file mod_pot_ljc_pair.f90.
References mod_constants::dashline, and mod_inquire::inquire_file().
Variable Documentation
ljc_pair_dimers
type(ljc_pair_dimer) mod_pot_ljc_pair::ljc_pair_dimers
Definition at line 44 of file mod_pot_ljc_pair.f90.
Referenced by mod_loops::calc(), and calc_ljc_pair_cross().
mol2_ljc_pair
type(ljc_pair_molecule) mod_pot_ljc_pair::mol2_ljc_pair
Definition at line 30 of file mod_pot_ljc_pair.f90.