mod_constants Module Reference
mod_constants Module Reference
This module defines a set constants.
Variables
integer, parameter, public dp = selected_real_kind(15, 307)
integer, parameter, public sp = selected_real_kind(6, 37)
real(kind=dp), parameter, public pi = 3.14159265358979_DP
real(kind=dp), parameter, public deg2rad = 180.0_DP / PI
real(kind=dp), parameter, public kb = 0.0083144621_DP
real(kind=dp), parameter, public ccon = 1389.354578_DP
real(kind=dp), parameter, public fpzero = tiny(1.0_DP)
real(kind=dp), parameter, public fpinf = huge(1.0_DP)
real(kind=dp), parameter, public ms = 0.001_DP
character(len=11), parameter int_alphabet = '1234567890'
character(len=12), parameter float_alphabet = '.-1234567890'
character(len=66), parameter char_alphabet = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ._-1234567890 '
character(len=74), parameter dashline = repeat('-', 74)
character(len=100), parameter dashline1 = repeat('-', 100)
Detailed Description
This module defines a set constants.
Author
Felippe M. Colombari
Laboratório de Química Teórica, LQT – UFSCar
Date
- Dec, 2017
module created
Variable Documentation
ccon
real(kind = dp), parameter, public mod_constants::ccon = 1389.354578_DP
Definition at line 24 of file mod_constants.f90.
Referenced by mod_pot_bhc::calc_bhc_cross(), mod_pot_ljc::calc_ljc_cross(), and mod_pot_ljc_pair::calc_ljc_pair_cross().
char_alphabet
character(len = 66), parameter mod_constants::char_alphabet = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ._-1234567890 '
Definition at line 31 of file mod_constants.f90.
Referenced by mod_cmd_line::parse_arguments().
dashline
character(len = 74), parameter mod_constants::dashline = repeat('-', 74)
Definition at line 33 of file mod_constants.f90.
Referenced by mod_pot_bhc::check_bhc_params(), mod_pot_ljc::check_ljc_params(), mod_read_molecules::check_molecule(), mod_read_grids::check_moves(), mod_resume::ending(), mod_cmd_line::parse_arguments(), mod_pot_bhc::read_bhc_params(), mod_pot_ljc_pair::read_ljc_pair_params(), mod_pot_ljc::read_ljc_params(), mod_resume::sort_output(), and themis().
dashline1
character(len = 100), parameter mod_constants::dashline1 = repeat('-', 100)
Definition at line 34 of file mod_constants.f90.
Referenced by mod_info::display_header().
deg2rad
real(kind = dp), parameter, public mod_constants::deg2rad = 180.0_DP / PI
Definition at line 22 of file mod_constants.f90.
Referenced by mod_read_molecules::rotate_molecule().
dp
integer, parameter, public mod_constants::dp = selected_real_kind(15, 307)
Definition at line 18 of file mod_constants.f90.
Referenced by themis(), and mod_vmd::WRITE_VMD_FILES::write_vmd_files().
float_alphabet
character(len = 12), parameter mod_constants::float_alphabet = '.-1234567890'
Definition at line 30 of file mod_constants.f90.
Referenced by mod_cmd_line::parse_arguments(), and mod_input_read::read_input_file().
fpinf
real(kind = dp), parameter, public mod_constants::fpinf = huge(1.0_DP)
Definition at line 26 of file mod_constants.f90.
Referenced by mod_input_read::read_input_file(), mod_search::sort_energy(), and mod_resume::sort_output().
fpzero
real(kind = dp), parameter, public mod_constants::fpzero = tiny(1.0_DP)
Definition at line 25 of file mod_constants.f90.
int_alphabet
character(len = 11), parameter mod_constants::int_alphabet = '1234567890'
Definition at line 29 of file mod_constants.f90.
Referenced by mod_input_read::read_input_file().
kb
real(kind = dp), parameter, public mod_constants::kb = 0.0083144621_DP
Definition at line 23 of file mod_constants.f90.
Referenced by mod_loops::calc(), mod_loops::calc_ztotal(), and mod_loops::recalc().
ms
real(kind = dp), parameter, public mod_constants::ms = 0.001_DP
Definition at line 27 of file mod_constants.f90.
pi
real(kind = dp), parameter, public mod_constants::pi = 3.14159265358979_DP
Definition at line 21 of file mod_constants.f90.
Referenced by mod_read_molecules::align_molecule().
sp
integer, parameter, public mod_constants::sp = selected_real_kind(6, 37)
Definition at line 19 of file mod_constants.f90.