mod_resume Module Reference
mod_resume Module Reference
This module contains routines that resume the run.
Functions/Subroutines
subroutine ending
This routine writes details of the calculation on screen.
subroutine sort_output
This routine sorts central grid points according to their free energy values.
Variables
real(kind=dp), dimension(:), allocatable a_min
integer, dimension(1) pos_a_min
Detailed Description
This module contains routines that resume the run.
Author
Felippe M. Colombari
Laboratório de Química Teórica, LQT – UFSCar
Date
- Jun, 2017
independent module created
Function/Subroutine Documentation
subroutine mod_resume::ending ()
This routine writes details of the calculation on screen.
Author
Felippe M. Colombari
Laboratório de Química Teórica, LQT – UFSCar
Date
- Jun, 2017
subroutine created
Definition at line 33 of file mod_resume.f90.
References mod_read_grids::a, mod_constants::dashline, mod_cmd_line::grid_type, mod_cmd_line::irun, mod_loops::min_ener, mod_search::n, mod_input_read::potential, mod_cmd_line::rad, mod_read_grids::repulsion, and mod_input_read::timet.
Referenced by themis().
subroutine mod_resume::sort_output ()
This routine sorts central grid points according to their free energy values.
Author
Felippe M. Colombari
Laboratório de Química Teórica, LQT – UFSCar
Date
- Aug, 2017
subroutine created
Note
The method used to sort the free energy array is non-standard, but is much more easier to implement and faster to run:
i) The lowest free energy value is found on array A and saved at first position of array B; ii) In array A, such position is replaced by INFINITY;
iii) Now the lowest free energy value from array A will be the second value from array B and so on...
Definition at line 104 of file mod_resume.f90.
References mod_read_grids::a, a_min, mod_loops::atotal, mod_constants::dashline, mod_read_grids::eavg, mod_loops::etotalavg, mod_constants::fpinf, mod_read_grids::grid_trans, mod_loops::kbt, mod_loops::min_ener, mod_read_grids::mts, mod_loops::mtstotal, pos_a_min, mod_read_grids::probt, and mod_loops::ztrans.
Referenced by themis().
Variable Documentation
real(kind = dp), dimension(:), allocatable mod_resume::a_min
Definition at line 19 of file mod_resume.f90.
Referenced by sort_output().
integer, dimension(1) mod_resume::pos_a_min
Definition at line 20 of file mod_resume.f90.
Referenced by sort_output().