mod_inquire Module Reference
mod_inquire Module Reference
This module performs inquire checks for all files that will be read.
Functions/Subroutines
subroutine inquire_file (file_unit, file_name, file_format, file_access)
Detailed Description
This module performs inquire checks for all files that will be read.
Author
Felippe M. Colombari
Laboratório de Química Teórica, LQT – UFSCar
Date
- Dec, 2017
module created
Function/Subroutine Documentation
inquire_file()
subroutine mod_inquire::inquire_file (integer, intent(in) file_unit, character(len = *), intent(in) file_name, character(len = *), intent(in) file_format, character(len = *), intent(in) file_access)
Definition at line 22 of file mod_inquire.f90.
Referenced by mod_pot_bhc::read_bhc_params(), mod_read_grids::read_grid(), mod_input_read::read_input_file(), mod_pot_ljc_pair::read_ljc_pair_params(), mod_pot_ljc::read_ljc_params(), mod_read_molecules::read_molecule(), mod_loops::recalc(), and mod_search::search_structures().