mod_search Module Reference
mod_search Module Reference
This module contains routines to search and write the lowest energy structures for the run.
Functions/Subroutines
subroutine count_structures
This routine counts the number of structures with energy closer (within 0.5 * kBT) to the most stable one.
subroutine sort_energy
This routine sorts the energy array and write its first n values to energy-sort.log.
subroutine search_structures
This routine generates the configurations for structures written at energy-sort.log.
Variables
integer, dimension(3) pos_min_energy
integer n
real(kind=dp) lowest
real(kind=dp), dimension(:), allocatable energy_ordered
Detailed Description
This module contains routines to search and write the lowest energy structures for the run.
Author
Felippe M. Colombari
Laboratório de Química Teórica, LQT – UFSCar
Date
- Sep, 2017
independent module created
- Jan, 2018
documentation and support added
Function/Subroutine Documentation
count_structures()
subroutine mod_search::count_structures ()
This routine counts the number of structures with energy closer (within 0.5 * kBT) to the most stable one.
Author
Felippe M. Colombari Laboratório de Química Teórica, LQT – UFSCar
Definition at line 36 of file mod_search.f90.
References mod_read_grids::grid_reo, mod_read_grids::grid_trans, mod_input_read::gyr_factor, mod_input_read::inter_energy, mod_loops::kbt, mod_loops::min_ener, and n.
Referenced by themis().
search_structures()
subroutine mod_search::search_structures ()
This routine generates the configurations for structures written at energy-sort.log.
Author
Felippe M. Colombari
Laboratório de Química Teórica, LQT – UFSCar
Date
- Sep, 2017
subroutine created
Definition at line 150 of file mod_search.f90.
References mod_read_molecules::cosphir, mod_read_molecules::costhetar, mod_read_molecules::dimers, energy_ordered, mod_read_grids::grid_reo, mod_read_grids::grid_trans, mod_inquire::inquire_file(), lowest, mod_read_molecules::mol1, mod_read_molecules::mol2, mod_input_read::nstruc, mod_read_grids::phir, mod_input_read::ref1, mod_input_read::ref2, mod_read_molecules::sinphir, mod_read_molecules::sinthetar, mod_read_grids::thetar, mod_input_read::vector1, and mod_input_read::vector2.
Referenced by themis().
sort_energy()
subroutine mod_search::sort_energy ()
This routine sorts the energy array and write its first n values to energy-sort.log.
Author
Felippe M. Colombari
Laboratório de Química Teórica, LQT – UFSCar
Date
- Sep, 2017
subroutine created
Note
The method used to sort the energy array is non-standard, but is much more easier to implement and faster to run:
i) The lowest energy value is found on array A and saved at first position of array B; ii) In array A, such position is replaced by INFINITY;
iii) Now the lowest energy value from array A will be the second value from array B and so on...
Definition at line 87 of file mod_search.f90.
References energy_ordered, mod_constants::fpinf, mod_input_read::inter_energy, mod_loops::kbt, mod_loops::min_ener, mod_input_read::nstruc, pos_min_energy, and mod_loops::ztrans.
Referenced by themis().
Variable Documentation
energy_ordered
real(kind = dp), dimension(:), allocatable mod_search::energy_ordered
Definition at line 24 of file mod_search.f90.
Referenced by search_structures(), and sort_energy().
lowest
real(kind = dp) mod_search::lowest
Definition at line 23 of file mod_search.f90.
Referenced by search_structures().
n
integer mod_search::n
Definition at line 22 of file mod_search.f90.
Referenced by count_structures(), and mod_resume::ending().
pos_min_energy
integer, dimension(3) mod_search::pos_min_energy
Definition at line 22 of file mod_search.f90.
Referenced by sort_energy().