mod_input_read Module Reference
mod_input_read Module Reference
This module contains a routine for INPUT reading and checking.
Functions/Subroutines
subroutine read_input
subroutine input_errors (num_line, keyword, attribute, msg_line)
subroutine check_keys
Variables
real(kind=dp) timet
integer finish
integer start
integer rate2
character(len=250) msg_line = char(0)
character(len=240) mopac_head = char(0)
character(len=10) potential = char(0)
character(len=10) writeframe = char(0)
character(len=5) wrtxtc = char(0)
real(kind=dp) temp = 0.0
real(kind=dp) rcut = 0.0
real(kind=dp) rcut_sqr = 0.0
real(kind=dp) maxp = 0.0
integer trans_factor = 0
integer rot_factor = 0
integer np = 0
integer ref1 = 0
integer ref2 = 0
integer vector1 = 0
integer vector2 = 0
integer nstruc = 0
logical key_translation_grid = .false.
logical key_rotation_grid = .false.
logical key_rotation_axis = .false.
logical key_potential = .false.
logical key_temperature = .false.
logical key_write_frames = .false.
logical key_ref_mol1 = .false.
logical key_ref_mol2 = .false.
logical key_rot_ref_mol1 = .false.
logical key_rot_ref_mol2 = .false.
logical key_shortest_distance = .false.
logical key_write_xtc = .false.
logical key_lowest_structures = .false.
logical key_mopac_job = .false.
Detailed Description
This module contains a routine for INPUT reading and checking.
Author
Felippe M. Colombari
Laboratório de Química Teórica, LQT – UFSCar
Date
- Jun, 2017
independent module created
- Jan, 2018
support added
Function/Subroutine Documentation
subroutine mod_input_read::check_keys ()
Definition at line 463 of file mod_input_read.f90.
References key_lowest_structures, key_mopac_job, key_potential, key_ref_mol1, key_ref_mol2, key_rot_ref_mol1, key_rot_ref_mol2, key_rotation_axis, key_rotation_grid, key_shortest_distance, key_temperature, key_translation_grid, key_write_frames, key_write_xtc, and writeframe.
Referenced by read_input().
subroutine mod_input_read::input_errors (integer, intent(in) num_line, character(len = 240), intent(in) keyword, character(len = 240), intent(in) attribute, character(len = 240), intent(in) msg_line)
Definition at line 442 of file mod_input_read.f90.
References mod_constants::dashline.
Referenced by read_input().
subroutine mod_input_read::read_input ()
Definition at line 62 of file mod_input_read.f90.
References check_keys(), mod_constants::float_alphabet, input_errors(), mod_inquire::inquire_check(), mod_constants::int_alphabet, key_lowest_structures, key_mopac_job, key_potential, key_ref_mol1, key_ref_mol2, key_rot_ref_mol1, key_rot_ref_mol2, key_rotation_axis, key_rotation_grid, key_shortest_distance, key_temperature, key_translation_grid, key_write_frames, key_write_xtc, maxp, mopac_head, msg_line, np, nstruc, potential, rcut, rcut_sqr, ref1, ref2, rot_factor, temp, trans_factor, vector1, vector2, writeframe, and wrtxtc.
Referenced by themis().
Variable Documentation
integer mod_input_read::finish
Definition at line 22 of file mod_input_read.f90.
Referenced by themis().
logical mod_input_read::key_lowest_structures = .false.
Definition at line 56 of file mod_input_read.f90.
Referenced by check_keys(), and read_input().
logical mod_input_read::key_mopac_job = .false.
Definition at line 57 of file mod_input_read.f90.
Referenced by check_keys(), and read_input().
logical mod_input_read::key_potential = .false.
Definition at line 47 of file mod_input_read.f90.
Referenced by check_keys(), and read_input().
logical mod_input_read::key_ref_mol1 = .false.
Definition at line 50 of file mod_input_read.f90.
Referenced by check_keys(), and read_input().
logical mod_input_read::key_ref_mol2 = .false.
Definition at line 51 of file mod_input_read.f90.
Referenced by check_keys(), and read_input().
logical mod_input_read::key_rot_ref_mol1 = .false.
Definition at line 52 of file mod_input_read.f90.
Referenced by check_keys(), and read_input().
logical mod_input_read::key_rot_ref_mol2 = .false.
Definition at line 53 of file mod_input_read.f90.
Referenced by check_keys(), and read_input().
logical mod_input_read::key_rotation_axis = .false.
Definition at line 46 of file mod_input_read.f90.
Referenced by check_keys(), and read_input().
logical mod_input_read::key_rotation_grid = .false.
Definition at line 45 of file mod_input_read.f90.
Referenced by check_keys(), and read_input().
logical mod_input_read::key_shortest_distance = .false.
Definition at line 54 of file mod_input_read.f90.
Referenced by check_keys(), and read_input().
logical mod_input_read::key_temperature = .false.
Definition at line 48 of file mod_input_read.f90.
Referenced by check_keys(), and read_input().
logical mod_input_read::key_translation_grid = .false.
Definition at line 44 of file mod_input_read.f90.
Referenced by check_keys(), and read_input().
logical mod_input_read::key_write_frames = .false.
Definition at line 49 of file mod_input_read.f90.
Referenced by check_keys(), and read_input().
logical mod_input_read::key_write_xtc = .false.
Definition at line 55 of file mod_input_read.f90.
Referenced by check_keys(), and read_input().
real(kind = dp) mod_input_read::maxp = 0.0
Definition at line 34 of file mod_input_read.f90.
Referenced by mod_read_grids::check_moves(), read_input(), and mod_read_xyz::rotate_xyz().
character(len = 240) mod_input_read::mopac_head = char(0)
Definition at line 27 of file mod_input_read.f90.
Referenced by read_input().
character(len = 250) mod_input_read::msg_line = char(0)
Definition at line 26 of file mod_input_read.f90.
Referenced by read_input().
integer mod_input_read::np = 0
Definition at line 37 of file mod_input_read.f90.
Referenced by mod_loops::calc(), mod_loops::calc_ztotal(), mod_read_grids::check_moves(), mod_search::count_structures(), read_input(), mod_loops::recalc(), and mod_read_xyz::rotate_xyz().
integer mod_input_read::nstruc = 0
Definition at line 42 of file mod_input_read.f90.
Referenced by read_input(), mod_search::search_structures(), and mod_search::sort_energy().
character(len = 10) mod_input_read::potential = char(0)
Definition at line 28 of file mod_input_read.f90.
Referenced by mod_loops::calc(), mod_deallocate_all::deallocate_arrays(), mod_resume::ending(), read_input(), mod_loops::recalc(), and themis().
integer mod_input_read::rate2
Definition at line 22 of file mod_input_read.f90.
Referenced by themis().
real(kind = dp) mod_input_read::rcut = 0.0
Definition at line 32 of file mod_input_read.f90.
Referenced by read_input().
real(kind = dp) mod_input_read::rcut_sqr = 0.0
Definition at line 33 of file mod_input_read.f90.
Referenced by mod_pot_ljc::calc_ljc_energy(), mod_pot_none::check_conf(), and read_input().
integer mod_input_read::ref1 = 0
Definition at line 38 of file mod_input_read.f90.
Referenced by mod_loops::calc(), mod_read_grids::center_translation_grid(), read_input(), and mod_search::search_structures().
integer mod_input_read::ref2 = 0
Definition at line 39 of file mod_input_read.f90.
Referenced by mod_loops::calc(), read_input(), and mod_search::search_structures().
integer mod_input_read::rot_factor = 0
Definition at line 36 of file mod_input_read.f90.
Referenced by mod_read_grids::build_rotation_sphere(), and read_input().
integer mod_input_read::start
Definition at line 22 of file mod_input_read.f90.
Referenced by themis().
real(kind = dp) mod_input_read::temp = 0.0
Definition at line 31 of file mod_input_read.f90.
Referenced by mod_loops::calc(), mod_loops::calc_ztotal(), read_input(), and mod_loops::recalc().
real(kind = dp) mod_input_read::timet
Definition at line 21 of file mod_input_read.f90.
Referenced by mod_resume::ending(), and themis().
integer mod_input_read::trans_factor = 0
Definition at line 35 of file mod_input_read.f90.
Referenced by mod_read_grids::build_translation_sphere(), and read_input().
integer mod_input_read::vector1 = 0
Definition at line 40 of file mod_input_read.f90.
Referenced by mod_loops::calc(), read_input(), and mod_search::search_structures().
integer mod_input_read::vector2 = 0
Definition at line 41 of file mod_input_read.f90.
Referenced by mod_loops::calc(), read_input(), and mod_search::search_structures().
character(len = 10) mod_input_read::writeframe = char(0)
Definition at line 29 of file mod_input_read.f90.
Referenced by mod_loops::calc(), check_keys(), and read_input().
character(len = 5) mod_input_read::wrtxtc = char(0)
Definition at line 30 of file mod_input_read.f90.
Referenced by mod_loops::calc(), and read_input().