mod_loops Module Reference
mod_loops Module Reference
This module contains the main program loop for Z(N,V,T) calculation.
Functions/Subroutines
subroutine calc
This routine performs the main loop and calls subroutine s to perform the configurational sampling and energy calculations.
subroutine recalc
This routine performs the main loop and reads already calculated energy values from energy file.
subroutine calc_ztotal
This routine performs partition function calculation for each grid point and also for the whole grid.
Variables
character(len=4) ntra
character(len=4) nreo
character(len=4) ngyr
real(kind=dp) t0
real(kind=dp) time
real(kind=dp) kbt
real(kind=dp) min_ener
real(kind=dp) atotal
real(kind=dp) mtstotal
real(kind=dp) etotalavg
real(kind=dp) ztrans
real(kind=dp) sumvexpvtrans
real(kind=dp), dimension(:), allocatable min_ener_t
integer tini
integer tend
integer rate
Detailed Description
This module contains the main program loop for Z(N,V,T) calculation.
Author
Felippe M. Colombari
Laboratório de Química Teórica, LQT – UFSCar
Date
- Oct, 2017
module created
Function/Subroutine Documentation
calc()
subroutine mod_loops::calc ()
This routine performs the main loop and calls subroutine s to perform the configurational sampling and energy calculations.
Author
Felippe M. Colombari
Laboratório de Química Teórica, LQT – UFSCar
Date
- Jun, 2017
subroutine created
energy values written in binary file
- Dec, 2017
lowest energy values are subtracted from each value to avoid problems due to exponential explosion
Definition at line 40 of file mod_loops.f90.
References mod_input_read::atom_overlap, mod_read_grids::check_moves(), mod_read_molecules::cosphir, mod_read_molecules::costhetar, mod_read_molecules::dimers, mod_read_grids::grid_reo, mod_read_grids::grid_trans, mod_input_read::gyr_factor, mod_input_read::inter_energy, mod_constants::kb, kbt, mod_pot_ljc_pair::ljc_pair_dimers, min_ener, min_ener_t, mod_read_molecules::mol1, mod_pot_bhc::mol1_bhc, mod_read_molecules::mol2, mod_pot_bhc::mol2_bhc, mod_pot_ljc::mol2_ljc, mod_read_grids::phir, mod_input_read::potential, rate, mod_input_read::ref2, mod_read_grids::rot_total, mod_read_molecules::sinphir, mod_read_molecules::sinthetar, mod_read_grids::sumvexpvrot, t0, mod_input_read::temp, tend, mod_read_grids::thetar, time, tini, mod_input_read::writeframe, mod_input_read::wrtxtc, and mod_read_grids::zrot.
Referenced by themis().
calc_ztotal()
subroutine mod_loops::calc_ztotal ()
This routine performs partition function calculation for each grid point and also for the whole grid.
Author
Felippe M. Colombari
Laboratório de Química Teórica, LQT – UFSCar
Date
- Jun, 2017
subroutine created
- Dec, 2017
absolute energy values are recovered and thermodynamic properties are obtained from them
- Mar, 2019
-TdS from ideal gas is subtracted from free energy
Definition at line 480 of file mod_loops.f90.
References mod_read_grids::a, atotal, mod_read_grids::eavg, etotalavg, mod_read_grids::grid_reo, mod_read_grids::grid_trans, mod_input_read::gyr_factor, mod_input_read::inter_energy, mod_constants::kb, kbt, min_ener, min_ener_t, mod_read_grids::mts, mtstotal, mod_read_grids::probt, mod_read_grids::sumvexpvrot, sumvexpvtrans, mod_input_read::temp, mod_read_grids::zrot, and ztrans.
Referenced by themis().
recalc()
subroutine mod_loops::recalc ()
This routine performs the main loop and reads already calculated energy values from energy file.
Author
Felippe M. Colombari
Laboratório de Química Teórica, LQT – UFSCar
Date
- Jun, 2017
subroutine created
energy values read from binary file
- Dec, 2017
lowest energy values are subtracted from each value to avoid problems in exponential calculation
Definition at line 327 of file mod_loops.f90.
References mod_read_grids::check_moves(), mod_read_grids::grid_reo, mod_read_grids::grid_trans, mod_input_read::gyr_factor, mod_inquire::inquire_file(), mod_input_read::inter_energy, mod_constants::kb, kbt, min_ener, min_ener_t, mod_input_read::potential, mod_input_read::scale_factor, mod_read_grids::sumvexpvrot, mod_input_read::temp, and mod_read_grids::zrot.
Referenced by themis().
Variable Documentation
atotal
real(kind = dp) mod_loops::atotal
Definition at line 19 of file mod_loops.f90.
Referenced by calc_ztotal(), and mod_resume::sort_output().
etotalavg
real(kind = dp) mod_loops::etotalavg
Definition at line 19 of file mod_loops.f90.
Referenced by calc_ztotal(), and mod_resume::sort_output().
kbt
real(kind = dp) mod_loops::kbt
Definition at line 18 of file mod_loops.f90.
Referenced by calc(), calc_ztotal(), mod_search::count_structures(), recalc(), mod_search::sort_energy(), and mod_resume::sort_output().
min_ener
real(kind = dp) mod_loops::min_ener
Definition at line 18 of file mod_loops.f90.
Referenced by calc(), calc_ztotal(), mod_search::count_structures(), mod_resume::ending(), recalc(), mod_search::sort_energy(), and mod_resume::sort_output().
min_ener_t
real(kind = dp), dimension(:), allocatable mod_loops::min_ener_t
Definition at line 21 of file mod_loops.f90.
Referenced by calc(), calc_ztotal(), mod_deallocate_all::deallocate_arrays(), and recalc().
mtstotal
real(kind = dp) mod_loops::mtstotal
Definition at line 19 of file mod_loops.f90.
Referenced by calc_ztotal(), and mod_resume::sort_output().
ngyr
character(len = 4) mod_loops::ngyr
Definition at line 17 of file mod_loops.f90.
nreo
character(len = 4) mod_loops::nreo
Definition at line 17 of file mod_loops.f90.
ntra
character(len = 4) mod_loops::ntra
Definition at line 17 of file mod_loops.f90.
rate
integer mod_loops::rate
Definition at line 22 of file mod_loops.f90.
Referenced by calc().
sumvexpvtrans
real(kind = dp) mod_loops::sumvexpvtrans
Definition at line 20 of file mod_loops.f90.
Referenced by calc_ztotal().
t0
real(kind = dp) mod_loops::t0
Definition at line 18 of file mod_loops.f90.
Referenced by calc().
tend
integer mod_loops::tend
Definition at line 22 of file mod_loops.f90.
Referenced by calc().
time
real(kind = dp) mod_loops::time
Definition at line 18 of file mod_loops.f90.
Referenced by calc().
tini
integer mod_loops::tini
Definition at line 22 of file mod_loops.f90.
Referenced by calc().
ztrans
real(kind = dp) mod_loops::ztrans
Definition at line 20 of file mod_loops.f90.
Referenced by calc_ztotal(), mod_search::sort_energy(), and mod_resume::sort_output().