mod_pot_ljc Module Reference
mod_pot_ljc Module Reference
This module performs LJ + coulombic potential calculations.
Data Types
type ljc_dimer
Functions/Subroutines
subroutine read_ljc_params (this, ljc_filename, numat)
This routine reads atom names, charges, sigma and epsilon values from parameter files.
subroutine check_ljc_params (this, mol, numat, ljc_filename)
This routine checks for inconsistent entries on parameter files.
subroutine calc_ljc_cross (this)
This routine calculates crossing values for LJ + coulomb potential before the loops.
subroutine calc_ljc_energy (this, g, r, t)
This routine calculates LJ + coulomb energy for each valid configuration.
Variables
type(ljc_molecules) mol2_ljc
type(ljc_dimer) ljc_dimers
Detailed Description
This module performs LJ + coulombic potential calculations.
Author
Felippe M. Colombari
Laboratório de Química Teórica, LQT – UFSCar
Date
- Oct, 2017
module created
Note
added error_handling
Date
- Nov 2019
Function/Subroutine Documentation
calc_ljc_cross()
subroutine mod_pot_ljc::calc_ljc_cross (class(ljc_dimer), intent(inout) this)
This routine calculates crossing values for LJ + coulomb potential before the loops.
Author
Felippe M. Colombari
Definition at line 153 of file mod_pot_ljc.f90.
References mod_constants::ccon, mod_read_molecules::mol1, mod_read_molecules::mol2, and mol2_ljc.
calc_ljc_energy()
subroutine mod_pot_ljc::calc_ljc_energy (class(ljc_dimer), intent(inout) this, integer, intent(in) g, integer, intent(in) r, integer, intent(in) t)
This routine calculates LJ + coulomb energy for each valid configuration.
Author
Felippe M. Colombari
Definition at line 195 of file mod_pot_ljc.f90.
References mod_input_read::atom_overlap, mod_input_read::inter_energy, mod_read_molecules::mol1, mod_read_molecules::mol2, mod_input_read::rcut_sqr, and mod_input_read::scale_factor.
check_ljc_params()
subroutine mod_pot_ljc::check_ljc_params (class(ljc_molecules), intent(inout) this, integer, intent(in) mol, integer, intent(in) numat, character(len = *), intent(in) ljc_filename)
This routine checks for inconsistent entries on parameter files.
Author
Felippe M. Colombari
Definition at line 107 of file mod_pot_ljc.f90.
References mod_constants::dashline.
read_ljc_params()
subroutine mod_pot_ljc::read_ljc_params (class(ljc_molecules), intent(inout) this, character(len = *), intent(in) ljc_filename, integer, intent(in) numat)
This routine reads atom names, charges, sigma and epsilon values from parameter files.
Author
Felippe M. Colombari
Definition at line 51 of file mod_pot_ljc.f90.
References mod_constants::dashline, and mod_inquire::inquire_file().
Variable Documentation
ljc_dimers
type(ljc_dimer) mod_pot_ljc::ljc_dimers
Definition at line 42 of file mod_pot_ljc.f90.
mol2_ljc
type(ljc_molecules) mod_pot_ljc::mol2_ljc
Definition at line 32 of file mod_pot_ljc.f90.
Referenced by mod_loops::calc(), calc_ljc_cross(), and mod_deallocate_all::deallocate_arrays().