mod_spherical_grids Module Reference
mod_spherical_grids Module Reference
Functions/Subroutines
subroutine icos_shape (point_num, edge_num, face_num, face_order_max, point_coord, edge_point, face_order, face_point)
subroutine icos_num (point_num, edge_num, face_num, face_order_max)
real(kind=dp) function r8vec_norm (n, a)
subroutine sphere_icos1_points (factor, node_num, node_xyz)
Detailed Description
Note
added error handling
Date
- Nov 2019
Function/Subroutine Documentation
icos_num()
subroutine mod_spherical_grids::icos_num (integer(kind=4) point_num, integer(kind=4) edge_num, integer(kind=4) face_num, integer(kind=4) face_order_max)
Definition at line 181 of file mod_spherical_grids.f90.
Referenced by sphere_icos1_points().
icos_shape()
subroutine mod_spherical_grids::icos_shape (integer(kind=4) point_num, integer(kind=4) edge_num, integer(kind=4) face_num, integer(kind=4) face_order_max, real(kind=dp), dimension(3,point_num) point_coord, integer(kind=4), dimension(edge_order,edge_num) edge_point, integer(kind=4), dimension(face_num) face_order, integer(kind=4), dimension(face_order_max,face_num) face_point)
Definition at line 14 of file mod_spherical_grids.f90.
Referenced by sphere_icos1_points().
r8vec_norm()
real(kind=dp) function mod_spherical_grids::r8vec_norm (integer(kind=4) n, real(kind=dp), dimension(n) a)
Definition at line 226 of file mod_spherical_grids.f90.
Referenced by sphere_icos1_points().
sphere_icos1_points()
subroutine mod_spherical_grids::sphere_icos1_points (integer(kind=4) factor, integer(kind=4) node_num, real(kind=dp), dimension(3,node_num) node_xyz)
Definition at line 274 of file mod_spherical_grids.f90.
References icos_num(), icos_shape(), and r8vec_norm().
Referenced by mod_read_grids::build_reorientation_sphere(), and mod_read_grids::build_translation_sphere().