mod_cmd_line Module Reference
mod_cmd_line Module Reference
This module contains a routine to get command line arguments.
Functions/Subroutines
subroutine parse_arguments
This routine parses the command line arguments.
subroutine command_line_errors (cmd_line_error)
subroutine display_help
subroutine display_license
Variables
real(kind=dp) rad = 0.0_dp
character(len=10) irun = char(0)
character(len=10) str_rad = char(0)
character(len=10) grid_type = char(0)
character(len=40) grid_transl = char(0)
character(len=20), dimension(:), allocatable arg
Detailed Description
This module contains a routine to get command line arguments.
Author
Felippe M. Colombari
Laboratório de Química Teórica, LQT – UFSCar
Date
- Jun, 2017
independent module created
Function/Subroutine Documentation
subroutine mod_cmd_line::command_line_errors (character(len = 256), intent(in) cmd_line_error)
Definition at line 192 of file mod_cmd_line.f90.
References arg, and mod_constants::dashline.
Referenced by parse_arguments().
subroutine mod_cmd_line::display_help ()
Definition at line 220 of file mod_cmd_line.f90.
References arg, and mod_constants::dashline.
Referenced by parse_arguments().
subroutine mod_cmd_line::display_license ()
Definition at line 299 of file mod_cmd_line.f90.
References arg, and mod_constants::dashline.
Referenced by parse_arguments().
subroutine mod_cmd_line::parse_arguments ()
This routine parses the command line arguments.
Author
Felippe M. Colombari
Laboratório de Química Teórica, LQT – UFSCar
Date
- Jun, 2017
subroutine created
- Dec, 2017
parsing tests added
Definition at line 39 of file mod_cmd_line.f90.
References arg, mod_constants::char_alphabet, command_line_errors(), mod_constants::dashline, display_help(), display_license(), mod_constants::float_alphabet, grid_transl, grid_type, irun, and rad.
Referenced by themis().
Variable Documentation
character(len = 20), dimension(:), allocatable mod_cmd_line::arg
Definition at line 24 of file mod_cmd_line.f90.
Referenced by command_line_errors(), display_help(), display_license(), and parse_arguments().
character(len = 40) mod_cmd_line::grid_transl = char(0)
Definition at line 23 of file mod_cmd_line.f90.
Referenced by parse_arguments(), and mod_read_grids::read_translation_grid().
character(len = 10) mod_cmd_line::grid_type = char(0)
Definition at line 22 of file mod_cmd_line.f90.
Referenced by mod_resume::ending(), parse_arguments(), and themis().
character(len = 10) mod_cmd_line::irun = char(0)
Definition at line 20 of file mod_cmd_line.f90.
Referenced by mod_deallocate_all::deallocate_arrays(), mod_resume::ending(), parse_arguments(), and themis().
real(kind = dp) mod_cmd_line::rad = 0.0_dp
Definition at line 19 of file mod_cmd_line.f90.
Referenced by mod_read_grids::build_translation_sphere(), mod_resume::ending(), and parse_arguments().
character(len = 10) mod_cmd_line::str_rad = char(0)
Definition at line 21 of file mod_cmd_line.f90.