mod_read_molecules Module Reference
mod_read_molecules Module Reference
This module reads coordinate files for xyz_files 1 and 2.
Data Types
type atom
type dimer
type molecule
Functions/Subroutines
subroutine calc_none_cross (this)
subroutine calc_none_energy (this, g, r, t)
This routine calculates interatomic distances and.
subroutine read_molecule (this, molecule_filename)
This routine reads coordinates for xyz_files 1 and 2.
subroutine check_molecule (this, reference, vector, mol_number)
This routine checks the reference sites molecules 1 and 2.
subroutine translate_molecule (this, reference)
This routine translates the molecule.
subroutine align_molecule (this, vector, reference)
This routine alings the molecule rotation vector along Z axis.
subroutine rotate_molecule (this, gyration)
This routine performs rotations of mol2 around mol1.
subroutine build_dimer (this)
subroutine write_xyz (this, lowest)
subroutine write_mop (this, header)
Variables
type(molecule) mol1
type(molecule) mol2
type(dimer) dimers
real(kind=dp) dtheta
real(kind=dp) dphi
real(kind=dp) dalpha
real(kind=dp) cosphi
real(kind=dp) sinphi
real(kind=dp) costheta
real(kind=dp) sintheta
real(kind=dp) cosalpha
real(kind=dp) sinalpha
real(kind=dp) cosphir = 0.0_DP
real(kind=dp) sinphir = 1.0_DP
real(kind=dp) costhetar = -1.0_DP
real(kind=dp) sinthetar = 0.0_DP
Detailed Description
This module reads coordinate files for xyz_files 1 and 2.
Author
Felippe M. Colombari Laboratório de Química Teórica, LQT – UFSCar
Note
Revision history
Date
Jan 2018: module created
Jul 2019: OO routine
Function/Subroutine Documentation
align_molecule()
subroutine mod_read_molecules::align_molecule (class(molecule), intent(inout) this, integer, intent(in) vector, integer, intent(in) reference)
This routine alings the molecule rotation vector along Z axis.
Author
Felippe M. Colombari Laboratório de Química Teórica, LQT – UFSCar
Definition at line 265 of file mod_read_molecules.f90.
References cosphi, costheta, dphi, dtheta, mod_constants::pi, sinphi, and sintheta.
build_dimer()
subroutine mod_read_molecules::build_dimer (class(dimer), intent(inout) this)
Definition at line 365 of file mod_read_molecules.f90.
References mol1, and mol2.
calc_none_cross()
subroutine mod_read_molecules::calc_none_cross (class(dimer), intent(inout) this)
Definition at line 61 of file mod_read_molecules.f90.
calc_none_energy()
subroutine mod_read_molecules::calc_none_energy (class(dimer), intent(inout) this, integer, intent(in) g, integer, intent(in) r, integer, intent(in) t)
This routine calculates interatomic distances and.
Author
Felippe M. Colombari
Definition at line 73 of file mod_read_molecules.f90.
References mod_input_read::atom_overlap, mod_input_read::inter_energy, mol1, and mol2.
check_molecule()
subroutine mod_read_molecules::check_molecule (class(molecule), intent(inout) this, integer, intent(in) reference, integer, intent(in) vector, integer, intent(in) mol_number)
This routine checks the reference sites molecules 1 and 2.
Author
Felippe M. Colombari Laboratório de Química Teórica, LQT – UFSCar
Note
Revision history
Date
Jul 2019: routine created
Definition at line 176 of file mod_read_molecules.f90.
References mod_constants::dashline.
read_molecule()
subroutine mod_read_molecules::read_molecule (class(molecule), intent(inout) this, character(len = *), intent(in) molecule_filename)
This routine reads coordinates for xyz_files 1 and 2.
Author
Felippe M. Colombari Laboratório de Química Teórica, LQT – UFSCar
Note
Revision history
Date
Jun 2017: first version
Oct 2017: modular routine
Jul 2019: OO routine
Definition at line 131 of file mod_read_molecules.f90.
References mod_inquire::inquire_file().
rotate_molecule()
subroutine mod_read_molecules::rotate_molecule (class(molecule), intent(inout) this, integer, intent(in) gyration)
This routine performs rotations of mol2 around mol1.
Author
Felippe M. Colombari Laboratório de Química Teórica, LQT – UFSCar
Definition at line 311 of file mod_read_molecules.f90.
References cosalpha, cosphir, costheta, costhetar, dalpha, mod_constants::deg2rad, mod_input_read::gyr_factor, mod_input_read::max_gyr, sinalpha, sinphir, sintheta, and sinthetar.
translate_molecule()
subroutine mod_read_molecules::translate_molecule (class(molecule), intent(inout) this, integer, intent(in) reference)
This routine translates the molecule.
Author
Felippe M. Colombari Laboratório de Química Teórica, LQT – UFSCar
Definition at line 240 of file mod_read_molecules.f90.
write_mop()
subroutine mod_read_molecules::write_mop (class(dimer), intent(inout) this, character(len = 128), intent(in) header)
Definition at line 430 of file mod_read_molecules.f90.
References mol1, and mol2.
write_xyz()
subroutine mod_read_molecules::write_xyz (class(dimer), intent(inout) this, real(kind = dp), intent(in) lowest)
Definition at line 398 of file mod_read_molecules.f90.
References mol1, and mol2.
Variable Documentation
cosalpha
real(kind = dp) mod_read_molecules::cosalpha
Definition at line 52 of file mod_read_molecules.f90.
Referenced by mod_read_grids::rotate_grid(), and rotate_molecule().
cosphi
real(kind = dp) mod_read_molecules::cosphi
Definition at line 52 of file mod_read_molecules.f90.
Referenced by mod_read_grids::align_grid(), and align_molecule().
cosphir
real(kind = dp) mod_read_molecules::cosphir = 0.0_DP
Definition at line 53 of file mod_read_molecules.f90.
Referenced by mod_loops::calc(), mod_read_grids::rotate_grid(), rotate_molecule(), and mod_search::search_structures().
costheta
real(kind = dp) mod_read_molecules::costheta
Definition at line 52 of file mod_read_molecules.f90.
Referenced by align_molecule(), mod_read_grids::rotate_grid(), and rotate_molecule().
costhetar
real(kind = dp) mod_read_molecules::costhetar = -1.0_DP
Definition at line 55 of file mod_read_molecules.f90.
Referenced by mod_loops::calc(), mod_read_grids::rotate_grid(), rotate_molecule(), and mod_search::search_structures().
dalpha
real(kind = dp) mod_read_molecules::dalpha
Definition at line 51 of file mod_read_molecules.f90.
Referenced by rotate_molecule().
dimers
type(dimer) mod_read_molecules::dimers
Definition at line 49 of file mod_read_molecules.f90.
Referenced by mod_loops::calc(), and mod_search::search_structures().
dphi
real(kind = dp) mod_read_molecules::dphi
Definition at line 51 of file mod_read_molecules.f90.
Referenced by align_molecule().
dtheta
real(kind = dp) mod_read_molecules::dtheta
Definition at line 51 of file mod_read_molecules.f90.
Referenced by align_molecule().
mol1
type(molecule) mod_read_molecules::mol1
Definition at line 36 of file mod_read_molecules.f90.
Referenced by build_dimer(), mod_loops::calc(), mod_pot_bhc::calc_bhc_cross(), mod_pot_bhc::calc_bhc_energy(), mod_pot_ljc::calc_ljc_cross(), mod_pot_ljc::calc_ljc_energy(), mod_pot_ljc_pair::calc_ljc_pair_cross(), mod_pot_ljc_pair::calc_ljc_pair_energy(), calc_none_energy(), mod_deallocate_all::deallocate_arrays(), mod_search::search_structures(), themis(), mod_read_grids::translate_grid(), write_mop(), and write_xyz().
mol2
type(molecule) mod_read_molecules::mol2
Definition at line 36 of file mod_read_molecules.f90.
Referenced by build_dimer(), mod_loops::calc(), mod_pot_bhc::calc_bhc_cross(), mod_pot_bhc::calc_bhc_energy(), mod_pot_ljc::calc_ljc_cross(), mod_pot_ljc::calc_ljc_energy(), mod_pot_ljc_pair::calc_ljc_pair_cross(), mod_pot_ljc_pair::calc_ljc_pair_energy(), calc_none_energy(), mod_deallocate_all::deallocate_arrays(), mod_search::search_structures(), themis(), write_mop(), and write_xyz().
sinalpha
real(kind = dp) mod_read_molecules::sinalpha
Definition at line 52 of file mod_read_molecules.f90.
Referenced by mod_read_grids::rotate_grid(), and rotate_molecule().
sinphi
real(kind = dp) mod_read_molecules::sinphi
Definition at line 52 of file mod_read_molecules.f90.
Referenced by mod_read_grids::align_grid(), and align_molecule().
sinphir
real(kind = dp) mod_read_molecules::sinphir = 1.0_DP
Definition at line 54 of file mod_read_molecules.f90.
Referenced by mod_loops::calc(), mod_read_grids::rotate_grid(), rotate_molecule(), and mod_search::search_structures().
sintheta
real(kind = dp) mod_read_molecules::sintheta
Definition at line 52 of file mod_read_molecules.f90.
Referenced by align_molecule(), mod_read_grids::rotate_grid(), and rotate_molecule().
sinthetar
real(kind = dp) mod_read_molecules::sinthetar = 0.0_DP
Definition at line 56 of file mod_read_molecules.f90.
Referenced by mod_loops::calc(), mod_read_grids::rotate_grid(), rotate_molecule(), and mod_search::search_structures().