mod_read_xyz Module Reference
mod_read_xyz Module Reference
This module reads coordinate files for xyz_files 1 and 2.
Data Types
type point
type xyz_dimer
type xyz_file
Functions/Subroutines
subroutine read_xyz (this, xyz_filename)
This routine reads coordinates for xyz_files 1 and 2.
subroutine translate_xyz (this, reference)
This routine places xyz_file 1 reference site at origin.
subroutine align_xyz (this, vector, reference)
This routine alings the molecule rotation vector along Z axis.
subroutine rotate_xyz (this, precession)
This routine performs rotations of mol2 around mol1.
subroutine build_dimer (this)
subroutine write_xyz (this, lowest)
Variables
type(xyz_file) mol1
type(xyz_file) mol2
type(xyz_dimer) dimers
real(kind=dp) dtheta
real(kind=dp) dphi
real(kind=dp) dalpha
real(kind=dp) cosphi
real(kind=dp) sinphi
real(kind=dp) costheta
real(kind=dp) sintheta
real(kind=dp) cosalpha
real(kind=dp) sinalpha
real(kind=dp) cosphir
real(kind=dp) sinphir
real(kind=dp) costhetar
real(kind=dp) sinthetar
Detailed Description
This module reads coordinate files for xyz_files 1 and 2.
Author
Felippe M. Colombari Laboratório de Química Teórica, LQT – UFSCar
Note
Revision history
Date
Jan 2018: module created
Function/Subroutine Documentation
subroutine mod_read_xyz::align_xyz (class(xyz_file), intent(inout) this, integer, intent(in) vector, integer, intent(in) reference)
This routine alings the molecule rotation vector along Z axis.
Author
Felippe M. Colombari Laboratório de Química Teórica, LQT – UFSCar
Definition at line 128 of file mod_read_xyz.f90.
References cosphi, costheta, dphi, dtheta, mod_constants::pi, sinphi, and sintheta.
subroutine mod_read_xyz::build_dimer (class(xyz_dimer), intent(inout) this)
Definition at line 228 of file mod_read_xyz.f90.
References mol1, and mol2.
subroutine mod_read_xyz::read_xyz (class(xyz_file), intent(inout) this, character(len = *), intent(in) xyz_filename)
This routine reads coordinates for xyz_files 1 and 2.
Author
Felippe M. Colombari Laboratório de Química Teórica, LQT – UFSCar
Note
Revision history
Date
Jun 2017: first version
Oct 2017: modular routine
Definition at line 60 of file mod_read_xyz.f90.
References mod_inquire::inquire_check().
subroutine mod_read_xyz::rotate_xyz (class(xyz_file), intent(inout) this, integer, intent(in) precession)
This routine performs rotations of mol2 around mol1.
Author
Felippe M. Colombari Laboratório de Química Teórica, LQT – UFSCar
Definition at line 174 of file mod_read_xyz.f90.
References cosalpha, cosphir, costheta, costhetar, dalpha, mod_constants::deg2rad, mod_input_read::maxp, mod_input_read::np, sinalpha, sinphir, sintheta, and sinthetar.
subroutine mod_read_xyz::translate_xyz (class(xyz_file), intent(inout) this, integer, intent(in) reference)
This routine places xyz_file 1 reference site at origin.
Author
Felippe M. Colombari Laboratório de Química Teórica, LQT – UFSCar
Definition at line 103 of file mod_read_xyz.f90.
subroutine mod_read_xyz::write_xyz (class(xyz_dimer), intent(inout) this, real(kind = dp), intent(in) lowest)
Definition at line 255 of file mod_read_xyz.f90.
References mol1, and mol2.
Variable Documentation
real(kind = dp) mod_read_xyz::cosalpha
Definition at line 45 of file mod_read_xyz.f90.
Referenced by rotate_xyz().
real(kind = dp) mod_read_xyz::cosphi
Definition at line 45 of file mod_read_xyz.f90.
Referenced by align_xyz().
real(kind = dp) mod_read_xyz::cosphir
Definition at line 46 of file mod_read_xyz.f90.
Referenced by mod_loops::calc(), rotate_xyz(), and mod_search::search_structures().
real(kind = dp) mod_read_xyz::costheta
Definition at line 45 of file mod_read_xyz.f90.
Referenced by align_xyz(), and rotate_xyz().
real(kind = dp) mod_read_xyz::costhetar
Definition at line 46 of file mod_read_xyz.f90.
Referenced by mod_loops::calc(), rotate_xyz(), and mod_search::search_structures().
real(kind = dp) mod_read_xyz::dalpha
Definition at line 44 of file mod_read_xyz.f90.
Referenced by rotate_xyz().
type(xyz_dimer) mod_read_xyz::dimers
Definition at line 42 of file mod_read_xyz.f90.
Referenced by mod_loops::calc(), and mod_search::search_structures().
real(kind = dp) mod_read_xyz::dphi
Definition at line 44 of file mod_read_xyz.f90.
Referenced by align_xyz().
real(kind = dp) mod_read_xyz::dtheta
Definition at line 44 of file mod_read_xyz.f90.
Referenced by align_xyz().
type(xyz_file) mod_read_xyz::mol1
Definition at line 33 of file mod_read_xyz.f90.
Referenced by build_dimer(), mod_loops::calc(), mod_pot_ljc::calc_ljc_cross(), mod_pot_ljc::calc_ljc_energy(), mod_read_grids::center_translation_grid(), mod_pot_none::check_conf(), mod_deallocate_all::deallocate_arrays(), mod_search::search_structures(), themis(), and write_xyz().
type(xyz_file) mod_read_xyz::mol2
Definition at line 33 of file mod_read_xyz.f90.
Referenced by build_dimer(), mod_loops::calc(), mod_pot_ljc::calc_ljc_cross(), mod_pot_ljc::calc_ljc_energy(), mod_pot_none::check_conf(), mod_deallocate_all::deallocate_arrays(), mod_search::search_structures(), themis(), and write_xyz().
real(kind = dp) mod_read_xyz::sinalpha
Definition at line 45 of file mod_read_xyz.f90.
Referenced by rotate_xyz().
real(kind = dp) mod_read_xyz::sinphi
Definition at line 45 of file mod_read_xyz.f90.
Referenced by align_xyz().
real(kind = dp) mod_read_xyz::sinphir
Definition at line 46 of file mod_read_xyz.f90.
Referenced by mod_loops::calc(), rotate_xyz(), and mod_search::search_structures().
real(kind = dp) mod_read_xyz::sintheta
Definition at line 45 of file mod_read_xyz.f90.
Referenced by align_xyz(), and rotate_xyz().
real(kind = dp) mod_read_xyz::sinthetar
Definition at line 46 of file mod_read_xyz.f90.
Referenced by mod_loops::calc(), rotate_xyz(), and mod_search::search_structures().