mod_read_grids Module Reference
mod_read_grids Module Reference
This module reads coordinate files for translation and rotation grids.
Data Types
type grid
type point
Functions/Subroutines
subroutine read_grid (this, grid_filename)
This routine reads coordinates for user-defined translation grid.
subroutine translate_grid (this)
This routine centers user-defined translation grid altogether with mol1.
subroutine align_grid (this)
This routine align user-defined translation grid along Z altogether with mol1.
subroutine rotate_grid (this)
subroutine build_translation_sphere (this, trans_factor, rad)
subroutine build_reorientation_sphere (this, reo_factor)
subroutine check_moves
This routine prints some checking information on screen.
Variables
type(grid) grid_trans
type(grid) grid_reo
real(kind=dp), dimension(:), allocatable a
real(kind=dp), dimension(:), allocatable mts
real(kind=dp), dimension(:), allocatable eavg
real(kind=dp), dimension(:), allocatable zrot
real(kind=dp), dimension(:), allocatable sumvexpvrot
real(kind=dp), dimension(:), allocatable probt
real(kind=dp), dimension(:), allocatable rr
real(kind=dp), dimension(:), allocatable thetar
real(kind=dp), dimension(:), allocatable phir
integer ntotal
integer rot_total
Detailed Description
This module reads coordinate files for translation and rotation grids.
Author
Felippe M. Colombari
Laboratório de Química Teórica, LQT – UFSCar
Date
- Jan, 2018
independent module created
- Jan, 2018
documentation and support added
Note
grids are standard XYZ coordinate files.
added error_handling Asdrubal Lozada-Blanco
Date
- Nov 2019
Function/Subroutine Documentation
align_grid()
subroutine mod_read_grids::align_grid (class(grid), intent(inout) this)
This routine align user-defined translation grid along Z altogether with mol1.
Author
Felippe M. Colombari
Laboratório de Química Teórica, LQT – UFSCar
Definition at line 130 of file mod_read_grids.f90.
References mod_read_molecules::cosphi, and mod_read_molecules::sinphi.
build_reorientation_sphere()
subroutine mod_read_grids::build_reorientation_sphere (class(grid), intent(inout) this, integer, intent(in) reo_factor)
Definition at line 258 of file mod_read_grids.f90.
References phir, rr, mod_spherical_grids::sphere_icos1_points(), and thetar.
build_translation_sphere()
subroutine mod_read_grids::build_translation_sphere (class(grid), intent(inout) this, integer, intent(in) trans_factor, real(kind = dp), intent(in) rad)
Definition at line 221 of file mod_read_grids.f90.
References mod_spherical_grids::sphere_icos1_points().
check_moves()
subroutine mod_read_grids::check_moves ()
This routine prints some checking information on screen.
Author
Felippe M. Colombari
Laboratório de Química Teórica, LQT – UFSCar
Date
- Dec, 2017
subroutine created and documented
Definition at line 353 of file mod_read_grids.f90.
References mod_constants::dashline, grid_reo, grid_trans, mod_input_read::gyr_factor, mod_input_read::max_gyr, ntotal, and rot_total.
Referenced by mod_loops::calc(), and mod_loops::recalc().
read_grid()
subroutine mod_read_grids::read_grid (class(grid), intent(inout) this, character(len = *), intent(in) grid_filename)
This routine reads coordinates for user-defined translation grid.
Author
Felippe M. Colombari
Laboratório de Química Teórica, LQT – UFSCar
Date
- Jun, 2017
first version
- Dec, 2017
modular subroutine created
- Jan, 2018
final version, documentation and support
Definition at line 63 of file mod_read_grids.f90.
References mod_inquire::inquire_file().
rotate_grid()
subroutine mod_read_grids::rotate_grid (class(grid), intent(inout) this)
Definition at line 158 of file mod_read_grids.f90.
References mod_read_molecules::cosalpha, mod_read_molecules::cosphir, mod_read_molecules::costheta, mod_read_molecules::costhetar, mod_read_molecules::sinalpha, mod_read_molecules::sinphir, mod_read_molecules::sintheta, and mod_read_molecules::sinthetar.
translate_grid()
subroutine mod_read_grids::translate_grid (class(grid), intent(inout) this)
This routine centers user-defined translation grid altogether with mol1.
Author
Felippe M. Colombari
Laboratório de Química Teórica, LQT – UFSCar
Definition at line 107 of file mod_read_grids.f90.
References mod_read_molecules::mol1.
Variable Documentation
a
real(kind = dp), dimension(:), allocatable mod_read_grids::a
Definition at line 43 of file mod_read_grids.f90.
Referenced by mod_loops::calc_ztotal(), mod_resume::ending(), mod_resume::sort_output(), and mod_vmd::WRITE_VMD_FILES::write_vmd_files().
eavg
real(kind = dp), dimension(:), allocatable mod_read_grids::eavg
Definition at line 43 of file mod_read_grids.f90.
Referenced by mod_loops::calc_ztotal(), mod_resume::sort_output(), and mod_vmd::WRITE_VMD_FILES::write_vmd_files().
grid_reo
type(grid) mod_read_grids::grid_reo
Definition at line 41 of file mod_read_grids.f90.
Referenced by mod_loops::calc(), mod_loops::calc_ztotal(), check_moves(), mod_search::count_structures(), mod_deallocate_all::deallocate_arrays(), mod_loops::recalc(), mod_search::search_structures(), and themis().
grid_trans
type(grid) mod_read_grids::grid_trans
Definition at line 41 of file mod_read_grids.f90.
Referenced by mod_loops::calc(), mod_loops::calc_ztotal(), check_moves(), mod_search::count_structures(), mod_deallocate_all::deallocate_arrays(), mod_loops::recalc(), mod_search::search_structures(), mod_resume::sort_output(), and themis().
mts
real(kind = dp), dimension(:), allocatable mod_read_grids::mts
Definition at line 43 of file mod_read_grids.f90.
Referenced by mod_loops::calc_ztotal(), mod_resume::sort_output(), and mod_vmd::WRITE_VMD_FILES::write_vmd_files().
ntotal
integer mod_read_grids::ntotal
Definition at line 46 of file mod_read_grids.f90.
Referenced by check_moves().
phir
real(kind = dp), dimension(:), allocatable mod_read_grids::phir
Definition at line 45 of file mod_read_grids.f90.
Referenced by build_reorientation_sphere(), mod_loops::calc(), mod_deallocate_all::deallocate_arrays(), and mod_search::search_structures().
probt
real(kind = dp), dimension(:), allocatable mod_read_grids::probt
Definition at line 44 of file mod_read_grids.f90.
Referenced by mod_loops::calc_ztotal(), mod_deallocate_all::deallocate_arrays(), and mod_resume::sort_output().
rot_total
integer mod_read_grids::rot_total
Definition at line 46 of file mod_read_grids.f90.
Referenced by mod_loops::calc(), and check_moves().
rr
real(kind = dp), dimension(:), allocatable mod_read_grids::rr
Definition at line 45 of file mod_read_grids.f90.
Referenced by build_reorientation_sphere(), and mod_deallocate_all::deallocate_arrays().
sumvexpvrot
real(kind = dp), dimension(:), allocatable mod_read_grids::sumvexpvrot
Definition at line 44 of file mod_read_grids.f90.
Referenced by mod_loops::calc(), mod_loops::calc_ztotal(), mod_deallocate_all::deallocate_arrays(), and mod_loops::recalc().
thetar
real(kind = dp), dimension(:), allocatable mod_read_grids::thetar
Definition at line 45 of file mod_read_grids.f90.
Referenced by build_reorientation_sphere(), mod_loops::calc(), mod_deallocate_all::deallocate_arrays(), and mod_search::search_structures().
zrot
real(kind = dp), dimension(:), allocatable mod_read_grids::zrot
Definition at line 44 of file mod_read_grids.f90.
Referenced by mod_loops::calc(), mod_loops::calc_ztotal(), mod_deallocate_all::deallocate_arrays(), and mod_loops::recalc().