/home/alozada/THEMIS_DECEMBER/themis-dev_december/code/src/themis.f90 File Reference
themis.f90 File Reference
Functions/Subroutines
program themis
Main module of THEMIS.
Function/Subroutine Documentation
themis()
program themis ()
Main module of THEMIS.
Author
Felippe M. Colombari
Laboratório de Química Teórica, LQT – UFSCar
Date
- Jun, 2017
initial test version
- Oct, 2017
modular version
Definition at line 16 of file themis.f90.
References mod_loops::calc(), mod_loops::calc_ztotal(), mod_search::count_structures(), mod_constants::dashline, mod_deallocate_all::deallocate_arrays(), mod_info::display_header(), mod_constants::dp, mod_resume::ending(), mod_read_grids::grid_reo, mod_read_grids::grid_trans, mod_cmd_line::grid_transl, mod_cmd_line::grid_type, mod_cmd_line::irun, mod_read_molecules::mol1, mod_read_molecules::mol2, mod_cmd_line::parse_arguments(), mod_input_read::potential, mod_cmd_line::rad, mod_input_read::read_input_file(), mod_loops::recalc(), mod_input_read::ref1, mod_input_read::ref2, mod_input_read::reo_factor, mod_search::search_structures(), mod_search::sort_energy(), mod_resume::sort_output(), mod_input_read::trans_factor, mod_input_read::vector1, and mod_input_read::vector2.